# Generated by Django 5.1.4 on 2026-07-02 17:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tributo', models.CharField(choices=[('ICMS', 'ICMS'), ('ISS', 'ISS'), ('PIS', 'PIS'), ('COFINS', 'COFINS'), ('CBS', 'CBS'), ('IBS', 'IBS'), ('IS', 'Imposto Seletivo')], max_length=10)),
                ('cclasstrib', models.CharField(blank=True, max_length=6)),
                ('ncm_ou_servico', models.CharField(default='GERAL', max_length=20)),
                ('uf_municipio', models.CharField(blank=True, max_length=10)),
                ('regime_tributario', models.CharField(blank=True, choices=[('SN', 'Simples Nacional'), ('LP', 'Lucro Presumido'), ('LR', 'Lucro Real'), ('MEI', 'MEI')], max_length=5)),
                ('aliquota', models.DecimalField(decimal_places=4, max_digits=9)),
                ('reducao_base', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('fonte_normativa', models.CharField(max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tabela tributária versionada',
                'verbose_name_plural': 'Tabelas tributárias versionadas',
                'ordering': ['codigo_tributo', '-vigencia_inicio', 'ncm_ou_servico', 'uf_municipio'],
                'indexes': [models.Index(fields=['codigo_tributo', 'vigencia_inicio', 'vigencia_fim'], name='fiscal_rule_codigo__61d455_idx'), models.Index(fields=['ncm_ou_servico', 'uf_municipio', 'regime_tributario'], name='fiscal_rule_ncm_ou__83c54b_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperacaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('ambiente', models.CharField(choices=[('homologacao', 'Homologação'), ('producao', 'Produção')], default='homologacao', max_length=20)),
                ('data_emissao', models.DateField(default=django.utils.timezone.localdate)),
                ('regime_emitente', models.CharField(choices=[('SN', 'Simples Nacional'), ('LP', 'Lucro Presumido'), ('LR', 'Lucro Real'), ('MEI', 'MEI')], max_length=5)),
                ('regime_destinatario', models.CharField(blank=True, choices=[('SN', 'Simples Nacional'), ('LP', 'Lucro Presumido'), ('LR', 'Lucro Real'), ('MEI', 'MEI')], max_length=5)),
                ('valor_base', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tributos_calculados', models.JSONField()),
                ('versao_motor', models.CharField(default='reforma-tributaria-2026.1', max_length=40)),
                ('calculado_em', models.DateTimeField(auto_now_add=True)),
                ('documento_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operacoes_fiscais', to='contenttypes.contenttype')),
                ('tabelas_aplicadas', models.ManyToManyField(blank=True, related_name='operacoes', to='fiscal_rules.tabelatributaria')),
            ],
            options={
                'verbose_name': 'Operação fiscal calculada',
                'verbose_name_plural': 'Operações fiscais calculadas',
                'ordering': ['-calculado_em'],
            },
        ),
    ]
