# Generated by Django 5.1.4 on 2026-04-30 18:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_remove_cliente_ativo_and_more'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColunaPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('cor', models.CharField(default='#1677ff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Use uma cor hexadecimal valida.')])),
                ('eh_ganho', models.BooleanField(default=False)),
                ('eh_perdido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Coluna do pipeline',
                'verbose_name_plural': 'Colunas do pipeline',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TagCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('cor', models.CharField(default='#1677ff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Use uma cor hexadecimal valida.')])),
            ],
            options={
                'verbose_name': 'Tag CRM',
                'verbose_name_plural': 'Tags CRM',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='oportunidade',
            options={'ordering': ['ordem_no_kanban', '-criado_em'], 'verbose_name': 'Oportunidade', 'verbose_name_plural': 'Oportunidades'},
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='etapa',
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='clientes.contatocliente'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='data_fechamento_prevista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='ordem_no_kanban',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='origem',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades_responsavel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='probabilidade',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='AnexoCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='crm/anexos/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tamanho', models.PositiveIntegerField(default=0)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos_crm_enviados', to=settings.AUTH_USER_MODEL)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='crm.oportunidade')),
            ],
            options={
                'verbose_name': 'Anexo CRM',
                'verbose_name_plural': 'Anexos CRM',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='AtividadeCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligacao'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('reuniao', 'Reuniao'), ('visita', 'Visita'), ('tarefa', 'Tarefa'), ('nota', 'Nota')], max_length=20)),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('data_atividade', models.DateTimeField(blank=True, null=True)),
                ('data_vencimento', models.DateTimeField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='crm.oportunidade')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_crm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Atividade CRM',
                'verbose_name_plural': 'Atividades CRM',
                'ordering': ['concluida', 'data_vencimento', '-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='coluna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='crm.colunapipeline'),
        ),
        migrations.CreateModel(
            name='EmailCRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=255)),
                ('corpo', models.TextField()),
                ('destinatario_nome', models.CharField(blank=True, max_length=150)),
                ('destinatario_email', models.EmailField(max_length=254)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('erro', 'Erro')], default='rascunho', max_length=20)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_crm_enviados', to=settings.AUTH_USER_MODEL)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='crm.oportunidade')),
            ],
            options={
                'verbose_name': 'Email CRM',
                'verbose_name_plural': 'Emails CRM',
                'ordering': ['-enviado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipelines_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pipeline',
                'verbose_name_plural': 'Pipelines',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='colunapipeline',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='oportunidades', to='crm.tagcrm'),
        ),
    ]
