# Generated by Django 5.1.4 on 2026-04-30 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj_cpf',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='origem',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='segmento',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('prospect', 'Prospect'), ('bloqueado', 'Bloqueado')], db_index=True, default='ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('fisica', 'Pessoa fisica'), ('juridica', 'Pessoa juridica')], default='juridica', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='ContatoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('principal', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contato do cliente',
                'verbose_name_plural': 'Contatos dos clientes',
                'ordering': ['-principal', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EnderecoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cobranca', 'Cobranca'), ('entrega', 'Entrega'), ('servico', 'Servico'), ('outro', 'Outro')], default='servico', max_length=20)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=120)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cidade', models.CharField(max_length=120)),
                ('estado', models.CharField(max_length=2)),
                ('principal', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Endereco do cliente',
                'verbose_name_plural': 'Enderecos dos clientes',
                'ordering': ['-principal', 'cidade', 'logradouro'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligacao'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('reuniao', 'Reuniao'), ('observacao', 'Observacao')], max_length=20)),
                ('descricao', models.TextField()),
                ('data_contato', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='clientes.cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historico do cliente',
                'verbose_name_plural': 'Historicos dos clientes',
                'ordering': ['-data_contato', '-criado_em'],
            },
        ),
    ]
