# Generated by Django 5.1.4 on 2026-05-04 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_remove_cliente_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliente_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_grupo', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj_principal_grupo',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
