# Generated by Django 5.1.4 on 2026-07-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenarioTesteFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True)),
                ('entrada', models.JSONField()),
                ('resultado_esperado', models.JSONField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cenário de teste fiscal',
                'verbose_name_plural': 'Cenários de teste fiscal',
                'ordering': ['nome'],
            },
        ),
    ]
