# Generated by Django 5.1.4 on 2026-04-30 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('razao_social', models.CharField(blank=True, max_length=180)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('endereco', models.TextField(blank=True)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracoes/logo/')),
                ('cor_principal', models.CharField(default='#1677ff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Use uma cor hexadecimal valida.')])),
            ],
            options={
                'verbose_name': 'Configuracao da empresa',
                'verbose_name_plural': 'Configuracoes da empresa',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('email_destino', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Configuracao de notificacao',
                'verbose_name_plural': 'Configuracoes de notificacao',
                'ordering': ['tipo'],
            },
        ),
    ]
