# Generated by Django 5.1.4 on 2026-05-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_configuracaoos_configuracaofinanceira'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoClienteReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='configuracoes/clientes_ref/')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Logo de cliente referencia',
                'verbose_name_plural': 'Logos de clientes referencia',
                'ordering': ['ordem', 'criado_em'],
            },
        ),
    ]
