# Generated by Django 5.1.4 on 2026-05-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_logoclientereferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoempresa',
            name='aliquota_cofins_padrao',
            field=models.DecimalField(blank=True, decimal_places=4, default=3.0, max_digits=6, verbose_name='Alíquota COFINS padrão (%)'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='aliquota_csll_padrao',
            field=models.DecimalField(blank=True, decimal_places=4, default=1.0, max_digits=6, verbose_name='Alíquota CSLL padrão (%)'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='aliquota_irpj_padrao',
            field=models.DecimalField(blank=True, decimal_places=4, default=1.5, max_digits=6, verbose_name='Alíquota IRPJ padrão (%)'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='aliquota_issqn_padrao',
            field=models.DecimalField(blank=True, decimal_places=4, default=5.0, max_digits=6, verbose_name='Alíquota ISSQN padrão (%)'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='aliquota_pis_padrao',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.65, max_digits=6, verbose_name='Alíquota PIS padrão (%)'),
        ),
        migrations.AddField(
            model_name='configuracaoempresa',
            name='regime_tributario',
            field=models.CharField(blank=True, choices=[('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real'), ('mei', 'MEI')], default='simples_nacional', help_text='Regime tributário da empresa usado automaticamente no faturamento.', max_length=30, verbose_name='Regime Tributário'),
        ),
    ]
