# Generated by Django 5.1.4 on 2026-05-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0006_remove_empresas_genericas_vazias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoempresa',
            name='regime_tributario',
            field=models.CharField(blank=True, choices=[('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real'), ('mei', 'MEI')], default='lucro_presumido', help_text='Regime tributário da empresa usado automaticamente no faturamento.', max_length=30, verbose_name='Regime Tributário'),
        ),
    ]
