# Generated by Django 5.1.4 on 2026-05-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0008_aplica_lucro_presumido_empresa_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoempresa',
            name='instagram',
            field=models.CharField(blank=True, help_text='URL ou usuário do Instagram', max_length=100),
        ),
    ]
