# Generated by Django 5.1.4 on 2026-05-06 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=200)),
                ('razao_social', models.CharField(blank=True, max_length=300)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('nome_responsavel', models.CharField(max_length=150)),
                ('email_responsavel', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('login_admin', models.EmailField(help_text='Email de acesso ao ERP/Facilities', max_length=254, unique=True)),
                ('senha_provisoria', models.CharField(blank=True, max_length=100)),
                ('schema_name', models.CharField(blank=True, help_text='Schema django-tenants (preencher ao criar tenant)', max_length=63)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='trial', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente SaaS',
                'verbose_name_plural': 'Clientes SaaS',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LogAcessoMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('acao', models.CharField(max_length=200)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Acesso Master',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PlanoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sistema', models.CharField(choices=[('erp', 'ERP Nexus'), ('facilities', 'Facilities SaaS'), ('ambos', 'ERP + Facilities')], default='erp', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_usuarios', models.IntegerField(default=5)),
                ('limite_registros', models.IntegerField(default=1000, help_text='OS, chamados, etc.')),
                ('recursos', models.JSONField(blank=True, default=list, help_text='["financeiro","crm","estoque"]')),
                ('destaque', models.BooleanField(default=False, help_text='Mostrar como recomendado')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['sistema', 'valor_mensal'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaSaaS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('trial', 'Trial'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado'), ('suspenso', 'Suspenso')], default='trial', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, help_text='Null = sem prazo de vencimento', null=True)),
                ('data_proximo_vencimento', models.DateField(blank=True, null=True)),
                ('valor_negociado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('motivo_desconto', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='master_admin.clientesaas')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='master_admin.planocatalogo')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoMensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(help_text='YYYY-MM (ex: 2025-03)', max_length=7)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('pix', 'PIX'), ('boleto', 'Boleto'), ('cartao', 'Cartão'), ('transferencia', 'Transferência'), ('dinheiro', 'Dinheiro')], max_length=20)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='master/comprovantes/')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='master_admin.assinaturasaas')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_vencimento'],
                'unique_together': {('assinatura', 'referencia')},
            },
        ),
    ]
