# Generated by Django 5.1.4 on 2026-04-30 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('aguardando', 'Aguardando'), ('concluida', 'Concluida'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('data_agendada', models.DateTimeField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='ordens/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
