# Generated by Django 5.1.4 on 2026-04-30 18:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_remove_cliente_ativo_and_more'),
        ('ordens', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Ordem de servico', 'verbose_name_plural': 'Ordens de servico'},
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='anexo',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='aprovado_por',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_atualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='condicao_pagamento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='contato_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_responsavel', to='clientes.contatocliente'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_emissao_nf',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_recebimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='descricao_servico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='endereco_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='clientes.enderecocliente'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='equipamento_marca',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='equipamento_modelo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='equipamento_serie',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='forma_cobranca',
            field=models.CharField(blank=True, choices=[('boleto', 'Boleto'), ('pix', 'Pix'), ('cartao', 'Cartao'), ('transferencia', 'Transferencia'), ('dinheiro', 'Dinheiro')], max_length=30),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='hora_conclusao',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='numero_nf',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='numero_pc',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='observacoes_tecnicas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='origem_lead',
            field=models.CharField(blank=True, choices=[('indicacao', 'Indicacao'), ('site', 'Site'), ('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('email', 'Email'), ('outro', 'Outro')], max_length=30),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pdf_nf',
            field=models.FileField(blank=True, null=True, upload_to='ordens/notas_fiscais/'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pdf_orcamento',
            field=models.FileField(blank=True, null=True, upload_to='ordens/orcamentos/'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pdf_pc',
            field=models.FileField(blank=True, null=True, upload_to='ordens/pedidos_compra/'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pdf_relatorio',
            field=models.FileField(blank=True, null=True, upload_to='ordens/relatorios/'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='pendente', max_length=30),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tem_pedido_compra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_relatorio',
            field=models.CharField(blank=True, choices=[('simples', 'Simples'), ('tecnico', 'Tecnico'), ('fotografico', 'Fotografico')], max_length=30),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_servico',
            field=models.CharField(choices=[('hvac', 'HVAC'), ('refrigeracao', 'Refrigeracao'), ('eletrica', 'Eletrica'), ('civil', 'Civil'), ('manutencao', 'Manutencao'), ('instalacao', 'Instalacao'), ('outro', 'Outro')], default='outro', max_length=30),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='validade_orcamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='validade_pc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_autorizado_pc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_final_faturado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_total_orcado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_agendada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('aberta', 'Aberta'), ('orcamento_enviado', 'Orcamento enviado'), ('aprovada', 'Aprovada'), ('agendada', 'Agendada'), ('em_execucao', 'Em execucao'), ('concluida', 'Concluida'), ('faturada', 'Faturada'), ('cancelada', 'Cancelada')], default='aberta', max_length=30),
        ),
        migrations.CreateModel(
            name='AssinaturaClienteOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_assinatura', models.ImageField(upload_to='ordens/assinaturas/')),
                ('nome_signatario', models.CharField(max_length=150)),
                ('data_assinatura', models.DateTimeField(default=django.utils.timezone.now)),
                ('os', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_cliente', to='ordens.ordemservico')),
            ],
            options={
                'verbose_name': 'Assinatura do cliente na OS',
                'verbose_name_plural': 'Assinaturas dos clientes nas OS',
            },
        ),
        migrations.CreateModel(
            name='ChatOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='ordens.ordemservico')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_os', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem da OS',
                'verbose_name_plural': 'Mensagens da OS',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AnexoChatOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='ordens/chat/')),
                ('nome_original', models.CharField(max_length=255)),
                ('mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='ordens.chatos')),
            ],
            options={
                'verbose_name': 'Anexo do chat da OS',
                'verbose_name_plural': 'Anexos do chat da OS',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DespesaOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('material', 'Material'), ('deslocamento', 'Deslocamento'), ('alimentacao', 'Alimentacao'), ('terceiro', 'Terceiro'), ('outro', 'Outro')], max_length=30)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='ordens/despesas/')),
                ('data_despesa', models.DateField(default=django.utils.timezone.localdate)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='ordens.ordemservico')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_os_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa da OS',
                'verbose_name_plural': 'Despesas da OS',
                'ordering': ['-data_despesa', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FotoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('antes', 'Antes'), ('depois', 'Depois')], max_length=10)),
                ('arquivo', models.ImageField(upload_to='ordens/fotos/')),
                ('legenda', models.CharField(blank=True, max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_os_enviadas', to=settings.AUTH_USER_MODEL)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ordens.ordemservico')),
            ],
            options={
                'verbose_name': 'Foto da OS',
                'verbose_name_plural': 'Fotos da OS',
                'ordering': ['ordem', 'enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ordens.ordemservico')),
            ],
            options={
                'verbose_name': 'Item do orcamento',
                'verbose_name_plural': 'Itens do orcamento',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LogStatusOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(blank=True, max_length=30)),
                ('status_novo', models.CharField(max_length=30)),
                ('alterado_em', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_status_os', to=settings.AUTH_USER_MODEL)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_status', to='ordens.ordemservico')),
            ],
            options={
                'verbose_name': 'Log de status da OS',
                'verbose_name_plural': 'Logs de status da OS',
                'ordering': ['-alterado_em'],
            },
        ),
    ]
