# Generated by Django 5.1.4 on 2026-04-30 19:12

import uuid
from django.db import migrations, models


def preencher_tokens(apps, schema_editor):
    OrdemServico = apps.get_model('ordens', 'OrdemServico')
    for ordem in OrdemServico.objects.filter(token_relatorio__isnull=True):
        ordem.token_relatorio = uuid.uuid4()
        ordem.save(update_fields=['token_relatorio'])


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0003_alter_ordemservico_options_remove_ordemservico_anexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='token_relatorio',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(preencher_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ordemservico',
            name='token_relatorio',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
