# Generated by Django 5.1.4 on 2026-05-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0004_ordemservico_token_relatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='dados_impostos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='total_com_impostos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_materiais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_servicos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
