# Generated by Django 5.1.4 on 2026-05-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0003_servico"),
        ("ordens", "0005_ordemservico_dados_impostos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemorcamento",
            name="codigo_referencia",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="itemorcamento",
            name="origem_tipo",
            field=models.CharField(
                choices=[("produto", "Produto"), ("servico", "Serviço"), ("avulso", "Item avulso")],
                default="avulso",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="itemorcamento",
            name="produto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens_orcamento",
                to="estoque.produto",
            ),
        ),
        migrations.AddField(
            model_name="itemorcamento",
            name="servico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="itens_orcamento",
                to="estoque.servico",
            ),
        ),
        migrations.AddField(
            model_name="itemorcamento",
            name="unidade_referencia",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
