# Generated by Django 5.1.4 on 2026-05-03 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_alter_cliente_options_remove_cliente_ativo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ordens", "0006_itemorcamento_origem_tipo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="dados_pc_extraidos",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="pc_confianca",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="pc_ultima_analise_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="resumo_pc",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="AprendizadoPedidoCompra",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("texto_extraido", models.TextField(blank=True)),
                ("descricao_confirmada", models.TextField(blank=True)),
                ("numero_pc_confirmado", models.CharField(blank=True, max_length=80)),
                ("valor_autorizado_confirmado", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("validade_confirmada", models.DateField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aprendizados_pedido_compra",
                        to="clientes.cliente",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aprendizados_pc_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "os",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aprendizados_pc",
                        to="ordens.ordemservico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aprendizado de pedido de compra",
                "verbose_name_plural": "Aprendizados de pedidos de compra",
                "ordering": ["-criado_em"],
            },
        ),
    ]
