# Generated by Django 5.1.4 on 2026-05-03 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0007_ordemservico_pc_inteligente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('hvac', 'HVAC'), ('refrigeracao', 'Refrigeração'), ('eletrica', 'Elétrica'), ('civil', 'Civil'), ('manutencao', 'Manutenção Preventiva'), ('instalacao', 'Instalação'), ('corretiva', 'Manutenção Corretiva'), ('outro', 'Outro')], max_length=30)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template de Checklist',
                'verbose_name_plural': 'Templates de Checklist',
                'ordering': ['tipo_servico', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('descricao_complementar', models.TextField(blank=True, help_text='Instrução ou detalhe sobre o item')),
                ('tipo_resposta', models.CharField(choices=[('sim_nao', 'Sim/Não'), ('texto', 'Texto livre'), ('numero', 'Número/Medida'), ('foto', 'Foto obrigatória'), ('multiplo', 'Múltiplos tipos (sim/não + texto + foto)')], default='sim_nao', max_length=20)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ordens.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Item de Checklist',
                'verbose_name_plural': 'Itens de Checklist',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RespostaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_bool', models.BooleanField(blank=True, null=True)),
                ('valor_texto', models.TextField(blank=True)),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('respondido_em', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='ordens.checklistitem')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_checklist', to='ordens.ordemservico')),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas_checklist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resposta de Checklist',
                'verbose_name_plural': 'Respostas de Checklist',
                'unique_together': {('os', 'item')},
            },
        ),
        migrations.CreateModel(
            name='FotoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='ordens/checklist_fotos/')),
                ('legenda', models.CharField(blank=True, max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_checklist_enviadas', to=settings.AUTH_USER_MODEL)),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ordens.respostachecklist')),
            ],
            options={
                'verbose_name': 'Foto do Checklist',
                'verbose_name_plural': 'Fotos do Checklist',
                'ordering': ['enviado_em'],
            },
        ),
    ]
