# Generated by Django 5.1.4 on 2026-05-03 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0008_checklisttemplate_checklistitem_respostachecklist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='aliquota_cbs',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=6, verbose_name='Alíquota CBS (%)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='aliquota_cofins',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=6, verbose_name='Alíquota COFINS (%)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='aliquota_csll',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=6, verbose_name='Alíquota CSLL (%)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='aliquota_ibs',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=6, verbose_name='Alíquota IBS (%)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='aliquota_irpj',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=6, verbose_name='Alíquota IRPJ (%)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='aliquota_issqn',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=6, verbose_name='Alíquota ISSQN (%)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='aliquota_pis',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=6, verbose_name='Alíquota PIS (%)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='descricao_servico_nf',
            field=models.TextField(blank=True, verbose_name='Descrição dos serviços para NF'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='municipio_incidencia_issqn',
            field=models.CharField(blank=True, max_length=80, verbose_name='Município de incidência ISSQN'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='retencao_issqn',
            field=models.BooleanField(default=False, verbose_name='Retenção ISSQN pelo tomador'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='situacao_tributaria_pis_cofins',
            field=models.CharField(blank=True, max_length=20, verbose_name='Situação Tributária PIS/COFINS'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_regime_tributario',
            field=models.CharField(blank=True, choices=[('simples', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real'), ('mei', 'MEI')], max_length=30, verbose_name='Regime Tributário'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_cbs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Valor CBS'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_cofins',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Valor COFINS'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_csll',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Valor CSLL'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_ibs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Valor IBS'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_irpj',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Valor IRPJ'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_issqn',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Valor ISSQN'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_liquido_nf',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Valor Líquido NF'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_pis',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Valor PIS'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_retido_issqn',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Valor Retido ISSQN'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_total_retencoes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Total Retenções'),
        ),
        migrations.CreateModel(
            name='FaturamentoAgrupado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_tomador', models.CharField(blank=True, max_length=18, verbose_name='CNPJ do tomador')),
                ('razao_social_tomador', models.CharField(blank=True, max_length=200, verbose_name='Razão Social do tomador')),
                ('endereco_tomador', models.CharField(blank=True, max_length=200)),
                ('email_tomador', models.CharField(blank=True, max_length=120)),
                ('valor_total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total_impostos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_liquido_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('numero_nf', models.CharField(blank=True, max_length=80)),
                ('data_emissao_nf', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('pdf_nf', models.FileField(blank=True, null=True, upload_to='nfs/agrupadas/')),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('faturado', 'Faturado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faturamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('ordens', models.ManyToManyField(blank=True, related_name='faturamentos_agrupados', to='ordens.ordemservico', verbose_name='Ordens de Serviço')),
            ],
            options={
                'verbose_name': 'Faturamento Agrupado',
                'verbose_name_plural': 'Faturamentos Agrupados',
                'ordering': ['-criado_em'],
            },
        ),
    ]
