# Generated by Django 5.1.4 on 2026-05-04 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_contabancaria_categoriafinanceira_lancamento_and_more'),
        ('ordens', '0010_checklists_tecnicos_padrao'),
        ('terceiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorcamento',
            name='custo_terceiro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='gerar_contas_pagar_terceiro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='lancamento_terceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_terceirizados', to='financeiro.lancamento'),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='markup_terceiro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='terceiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_orcamento', to='terceiros.terceirizado'),
        ),
    ]
