# Generated by Django 5.1.4 on 2026-05-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0011_itemorcamento_custo_terceiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
