# Generated by Django 5.1.4 on 2026-05-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0012_add_valor_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='percentual_desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_desconto',
            field=models.CharField(choices=[('valor', 'Valor fixo (R$)'), ('percentual', 'Percentual (%)')], default='valor', max_length=20),
        ),
    ]
