# Generated by Django 5.1.4 on 2026-05-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0013_add_tipo_percentual_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatos',
            name='origem',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='origem_referencia_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='origem_referencia_tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='origem_sistema',
            field=models.CharField(choices=[('erp', 'ERP Nexus'), ('facilities', 'Facilities')], default='erp', max_length=20),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tenant_contratante_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tenant_prestador_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
