# Generated by Django 5.1.4 on 2026-07-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0014_chatos_origem_ordemservico_origem_referencia_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='aliquota_irrf',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=6, verbose_name='Alíquota IRRF (%)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_irrf',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='Valor IRRF'),
        ),
    ]
