# Generated by Django 5.1.4 on 2026-05-05 23:31

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('nome', models.CharField(max_length=200)),
                ('razao_social', models.CharField(blank=True, max_length=300)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('tipo_produto', models.CharField(choices=[('erp', 'ERP Nexus (Prestador)'), ('facilities', 'Facilities Platform (Contratante)'), ('ambos', 'ERP + Facilities')], default='erp', max_length=20)),
                ('plano', models.CharField(choices=[('basico', 'Básico'), ('profissional', 'Profissional'), ('enterprise', 'Enterprise')], default='basico', max_length=20)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('cancelado', 'Cancelado')], default='trial', max_length=20)),
                ('email_admin', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('visivel_no_diretorio', models.BooleanField(default=False)),
                ('especialidades', models.JSONField(blank=True, default=list)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('descricao_servicos', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.client')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
