# Generated by Django 5.1.4 on 2026-04-30 18:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('ordens', '0003_alter_ordemservico_options_remove_ordemservico_anexo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('banco', models.CharField(blank=True, max_length=120)),
                ('agencia', models.CharField(blank=True, max_length=30)),
                ('conta', models.CharField(blank=True, max_length=40)),
                ('tipo', models.CharField(choices=[('corrente', 'Corrente'), ('poupanca', 'Poupanca'), ('caixa', 'Caixa'), ('investimento', 'Investimento')], default='corrente', max_length=20)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conta bancaria',
                'verbose_name_plural': 'Contas bancarias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=20)),
                ('cor', models.CharField(default='#1677ff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Use uma cor hexadecimal valida.')])),
                ('icone', models.CharField(blank=True, max_length=60)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorias', to='financeiro.categoriafinanceira')),
            ],
            options={
                'verbose_name': 'Categoria financeira',
                'verbose_name_plural': 'Categorias financeiras',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_competencia', models.DateField(default=django.utils.timezone.localdate)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('fornecedor_cliente', models.CharField(blank=True, max_length=180)),
                ('numero_documento', models.CharField(blank=True, max_length=80)),
                ('observacoes', models.TextField(blank=True)),
                ('recorrente', models.BooleanField(default=False)),
                ('frequencia_recorrencia', models.CharField(blank=True, choices=[('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='financeiro.categoriafinanceira')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='financeiro.contabancaria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros_criados', to=settings.AUTH_USER_MODEL)),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros', to='ordens.ordemservico')),
            ],
            options={
                'verbose_name': 'Lancamento financeiro',
                'verbose_name_plural': 'Lancamentos financeiros',
                'ordering': ['data_vencimento', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='AnexoLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='financeiro/lancamentos/')),
                ('nome_original', models.CharField(max_length=255)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='financeiro.lancamento')),
            ],
            options={
                'verbose_name': 'Anexo do lancamento',
                'verbose_name_plural': 'Anexos dos lancamentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TransferenciaEntreConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='financeiro.contabancaria')),
                ('conta_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_origem', to='financeiro.contabancaria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_financeiras_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia entre contas',
                'verbose_name_plural': 'Transferencias entre contas',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.DeleteModel(
            name='LancamentoFinanceiro',
        ),
    ]
