# Generated by Django 5.1.4 on 2026-05-08 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_categorias_produto_padrao'),
        ('financeiro', '0002_contabancaria_categoriafinanceira_lancamento_and_more'),
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='movimentacao_estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros', to='estoque.movimentacaoestoque'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_financeiros', to='loja.venda'),
        ),
    ]
