# Generated by Django 5.1.4 on 2026-07-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacaoPGDAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Use o primeiro dia do mês de competência.')),
                ('receita_faturada', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('receita_declarada', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rbt12_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iss_retido_fonte', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('divergencia', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('itens_auditoria', models.JSONField(blank=True, default=list)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conciliação PGDAS-D',
                'verbose_name_plural': 'Conciliações PGDAS-D',
                'ordering': ['-competencia'],
            },
        ),
    ]
