# Generated by Django 5.1.4 on 2026-05-02 13:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaImpostoLucroPresumido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=180)),
                ('pis', models.DecimalField(decimal_places=2, default=0.65, max_digits=5)),
                ('cofins', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('irpj_servicos', models.DecimalField(decimal_places=2, default=4.8, max_digits=5)),
                ('csll_servicos', models.DecimalField(decimal_places=2, default=2.88, max_digits=5)),
                ('irpj_comercio', models.DecimalField(decimal_places=2, default=1.2, max_digits=5)),
                ('csll_comercio', models.DecimalField(decimal_places=2, default=1.08, max_digits=5)),
                ('vigencia_inicio', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tabela de imposto do Lucro Presumido',
                'verbose_name_plural': 'Tabelas de impostos do Lucro Presumido',
                'ordering': ['-vigencia_inicio', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_tributario', models.CharField(choices=[('mei', 'MEI'), ('simples_nacional', 'Simples Nacional'), ('lucro_presumido', 'Lucro Presumido'), ('lucro_real', 'Lucro Real')], default='simples_nacional', max_length=30)),
                ('tipo_nota', models.CharField(choices=[('nfse', 'NFS-e'), ('nfe', 'NF-e'), ('ambas', 'Ambas')], default='nfse', max_length=10)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
                ('razao_social', models.CharField(blank=True, max_length=180)),
                ('municipio', models.CharField(blank=True, max_length=120)),
                ('codigo_municipio_ibge', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d*$', 'Use apenas números.')])),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('aliquota_iss', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('iss_retido_fonte', models.BooleanField(default=False)),
                ('codigo_servico_lc116', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracao_fiscal', to='configuracoes.configuracaoempresa')),
            ],
            options={
                'verbose_name': 'Configuração fiscal',
                'verbose_name_plural': 'Configurações fiscais',
            },
        ),
    ]
