# Generated by Django 5.1.4 on 2026-07-06 17:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0009_configuracaoempresa_instagram'),
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaofiscal',
            name='anexo_simples',
            field=models.CharField(choices=[('anexo_iii', 'Anexo III'), ('anexo_iv', 'Anexo IV')], default='anexo_iii', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracaofiscal',
            name='data_abertura_simples',
            field=models.DateField(default=datetime.date(2025, 12, 18)),
        ),
        migrations.CreateModel(
            name='ApuracaoSimplesNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Use sempre o primeiro dia do mês de competência.')),
                ('anexo', models.CharField(default='anexo_iii', max_length=20)),
                ('receita_mes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rbt12', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('meses_atividade', models.PositiveSmallIntegerField(default=1)),
                ('proporcionalizado', models.BooleanField(default=True)),
                ('faixa', models.PositiveSmallIntegerField(default=1)),
                ('aliquota_nominal', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('parcela_deduzir', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('aliquota_efetiva', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('das_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('percentual_sublimite', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('percentual_teto', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('alerta', models.CharField(choices=[('ok', 'Dentro dos limites'), ('perto_sublimite', 'Perto do sublimite'), ('acima_sublimite', 'Acima do sublimite'), ('perto_teto', 'Perto do teto'), ('acima_teto', 'Acima do teto')], default='ok', max_length=30)),
                ('memoria_calculo', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuracoes_simples', to='configuracoes.configuracaoempresa')),
            ],
            options={
                'verbose_name': 'Apuração do Simples Nacional',
                'verbose_name_plural': 'Apurações do Simples Nacional',
                'ordering': ['-competencia'],
                'indexes': [models.Index(fields=['empresa', 'competencia'], name='fiscal_apur_empresa_906763_idx'), models.Index(fields=['alerta'], name='fiscal_apur_alerta_d2f2db_idx')],
                'unique_together': {('empresa', 'competencia')},
            },
        ),
        migrations.CreateModel(
            name='FaturamentoMensalSimples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(help_text='Use sempre o primeiro dia do mês de competência.')),
                ('receita_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('nfse', 'NFS-e'), ('importacao', 'Importação')], default='manual', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturamentos_simples', to='configuracoes.configuracaoempresa')),
            ],
            options={
                'verbose_name': 'Faturamento mensal do Simples',
                'verbose_name_plural': 'Faturamentos mensais do Simples',
                'ordering': ['-competencia'],
                'indexes': [models.Index(fields=['empresa', 'competencia'], name='fiscal_fatu_empresa_938521_idx')],
                'unique_together': {('empresa', 'competencia')},
            },
        ),
    ]
