# Generated by Django 5.1.4 on 2026-07-06 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0009_configuracaoempresa_instagram'),
        ('fiscal', '0002_configuracaofiscal_anexo_simples_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersaoRegraSimplesNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('descricao', models.TextField(blank=True)),
                ('anexo', models.CharField(choices=[('anexo_iii', 'Anexo III'), ('anexo_iv', 'Anexo IV')], default='anexo_iii', max_length=20)),
                ('tabela_faixas', models.JSONField(blank=True, default=list, help_text='Lista de faixas com limite, aliquota e deduzir.')),
                ('sublimite', models.DecimalField(decimal_places=2, default=3600000, max_digits=14)),
                ('teto', models.DecimalField(decimal_places=2, default=4800000, max_digits=14)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_ate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativa', 'Ativa'), ('arquivada', 'Arquivada')], default='rascunho', max_length=20)),
                ('criado_por', models.CharField(blank=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes_regra_simples', to='configuracoes.configuracaoempresa')),
            ],
            options={
                'verbose_name': 'Versão de regra do Simples Nacional',
                'verbose_name_plural': 'Versões de regra do Simples Nacional',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SimulacaoFiscalSimples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('entrada', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('origem', models.CharField(choices=[('api', 'API'), ('manual', 'Manual'), ('sistema', 'Sistema')], default='api', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes_fiscais_simples', to='configuracoes.configuracaoempresa')),
                ('regra_versao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulacoes', to='fiscal.versaoregrasimplesnacional')),
            ],
            options={
                'verbose_name': 'Simulação fiscal do Simples',
                'verbose_name_plural': 'Simulações fiscais do Simples',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='versaoregrasimplesnacional',
            index=models.Index(fields=['empresa', 'status'], name='fiscal_vers_empresa_bdb915_idx'),
        ),
        migrations.AddIndex(
            model_name='versaoregrasimplesnacional',
            index=models.Index(fields=['empresa', 'anexo'], name='fiscal_vers_empresa_4da9e4_idx'),
        ),
        migrations.AddIndex(
            model_name='simulacaofiscalsimples',
            index=models.Index(fields=['empresa', 'competencia'], name='fiscal_simu_empresa_9620a8_idx'),
        ),
        migrations.AddIndex(
            model_name='simulacaofiscalsimples',
            index=models.Index(fields=['origem'], name='fiscal_simu_origem_306686_idx'),
        ),
    ]
