# Generated by Django 5.1.4 on 2026-05-06 17:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_type', models.CharField(max_length=50)),
                ('aggregate_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('processado', 'Processado'), ('falhou', 'Falhou')], default='pendente', max_length=20)),
                ('tentativas', models.IntegerField(default=0)),
                ('proxima_tentativa', models.DateTimeField()),
                ('erro_ultimo', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('tipo_servico', models.CharField(max_length=100)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('prazo_execucao_max_dias', models.IntegerField()),
                ('data_abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_encerramento', models.DateTimeField()),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicada', 'Publicada'), ('em_analise', 'Em Análise'), ('encerrada', 'Encerrada'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20)),
                ('tipo_julgamento', models.CharField(choices=[('menor_preco', 'Menor Preço'), ('melhor_tecnica', 'Melhor Técnica'), ('tecnica_preco', 'Técnica e Preço')], default='menor_preco', max_length=20)),
                ('documentos_anexos', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prestadores_convidados', models.ManyToManyField(blank=True, related_name='convites_licitacao', to='saas.tenant')),
                ('tenant_contratante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licitacoes_abertas', to='saas.tenant')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saas.unidade')),
            ],
            options={
                'verbose_name': 'Licitação',
                'verbose_name_plural': 'Licitações',
            },
        ),
        migrations.CreateModel(
            name='PropostaLicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_proposta', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviando', 'Enviando'), ('recebida', 'Recebida'), ('em_analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('prazo_execucao_dias', models.IntegerField()),
                ('condicao_pagamento', models.CharField(max_length=200)),
                ('validade_proposta', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('diferencial_competitivo', models.TextField(blank=True)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('analisada_em', models.DateTimeField(blank=True, null=True)),
                ('decidida_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_recusa', models.TextField(blank=True)),
                ('pontuacao_tecnica', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ranking_final', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('versao', models.IntegerField(default=1)),
                ('licitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='saas.licitacao')),
                ('tenant_prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_enviadas', to='saas.tenant')),
            ],
            options={
                'verbose_name': 'Proposta de Licitação',
                'verbose_name_plural': 'Propostas de Licitação',
                'unique_together': {('licitacao', 'tenant_prestador')},
            },
        ),
        migrations.CreateModel(
            name='ItemProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(max_length=20)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ordem', models.IntegerField(default=0)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='saas.propostalicitacao')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='EventoLicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=100)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('detalhes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saas.tenant')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('licitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='saas.licitacao')),
                ('proposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saas.propostalicitacao')),
            ],
        ),
    ]
