# Generated by Django 5.1.4 on 2026-05-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_categoriaproduto_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('hvac', 'HVAC'), ('refrigeracao', 'Refrigeração'), ('eletrica', 'Elétrica'), ('civil', 'Civil'), ('manutencao', 'Manutenção'), ('instalacao', 'Instalação')], default='hvac', max_length=50)),
                ('unidade_medida', models.CharField(choices=[('hora', 'Hora'), ('dia', 'Dia'), ('uni', 'Unitário'), ('lote', 'Lote')], default='uni', max_length=20)),
                ('preco_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tributacao', models.CharField(choices=[('iss', 'ISS'), ('icms', 'ICMS'), ('pis_cofins', 'PIS/COFINS')], default='iss', max_length=30)),
                ('codigo_lc116', models.CharField(blank=True, max_length=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['categoria', 'nome'],
            },
        ),
    ]
