# Generated by Django 5.1.4 on 2026-05-03 22:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaproduto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categoriaproduto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriaproduto',
            name='nome',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='motivo',
            field=models.CharField(choices=[('compra', 'Compra'), ('uso_os', 'Uso em OS'), ('perda', 'Perda'), ('ajuste_inventario', 'Ajuste de inventario'), ('devolucao', 'Devolucao'), ('consumo_interno', 'Consumo Interno'), ('amostra', 'Amostra')], max_length=30),
        ),
        migrations.CreateModel(
            name='AlertaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('estoque_baixo', 'Estoque Baixo'), ('sem_estoque', 'Sem Estoque'), ('fora_minimo', 'Fora do Mínimo')], default='estoque_baixo', max_length=50)),
                ('descricao', models.TextField()),
                ('lido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Alerta de Estoque',
                'verbose_name_plural': 'Alertas de Estoque',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['lido', '-criado_em'], name='estoque_ale_lido_a1005d_idx'), models.Index(fields=['produto'], name='estoque_ale_produto_fcaf44_idx')],
            },
        ),
    ]
