# Generated by Django 5.1.4 on 2026-05-04 16:44

from django.db import migrations, models


def atualizar_precos_sugeridos(apps, schema_editor):
    Produto = apps.get_model("estoque", "Produto")
    for produto in Produto.objects.all():
        produto.preco_venda_sugerido = produto.preco_venda or produto.preco_custo
        produto.preco_manual = bool(produto.preco_venda)
        produto.save(update_fields=["preco_venda_sugerido", "preco_manual"])


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_categoriaproduto_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='aliquota_impostos_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='despesas_operacionais_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='markup_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_venda_sugerido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_suprimento',
            field=models.CharField(choices=[('estoque', 'Alocado no estoque'), ('futuro', 'Produto futuro / sob compra')], default='estoque', max_length=20),
        ),
        migrations.RunPython(atualizar_precos_sugeridos, migrations.RunPython.noop),
    ]
