# Generated by Django 5.1.4 on 2026-05-27 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_categorias_produto_padrao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorInteligenciaConhecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('escopo', models.CharField(choices=[('geral', 'Geral'), ('orcamento', 'Orçamento'), ('catalogo', 'Catálogo'), ('financeiro', 'Financeiro'), ('estoque', 'Estoque')], default='geral', max_length=30)),
                ('tipo', models.CharField(choices=[('regra', 'Regra'), ('sinonimo', 'Sinônimo'), ('preco', 'Preço'), ('procedimento', 'Procedimento'), ('resposta', 'Resposta')], default='regra', max_length=30)),
                ('entrada', models.TextField(help_text='Frase, situação ou padrão que ativa este conhecimento.')),
                ('resposta', models.TextField(help_text='Como o motor deve agir ou responder.')),
                ('termos', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('confianca', models.PositiveIntegerField(default=80)),
                ('ativo', models.BooleanField(default=True)),
                ('vezes_usado', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conhecimentos_motor_criados', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conhecimentos_motor', to='estoque.produto')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conhecimentos_motor', to='estoque.servico')),
            ],
            options={
                'verbose_name': 'Conhecimento do motor',
                'verbose_name_plural': 'Conhecimentos do motor',
                'ordering': ['-atualizado_em', 'titulo'],
                'indexes': [models.Index(fields=['escopo', 'tipo', 'ativo'], name='estoque_mot_escopo_a7fd38_idx'), models.Index(fields=['ativo', '-atualizado_em'], name='estoque_mot_ativo_a1974d_idx')],
            },
        ),
    ]
