# Generated by Django 5.1.4 on 2026-05-27 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_motorinteligenciaconhecimento'),
        ('ordens', '0014_chatos_origem_ordemservico_origem_referencia_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='motorinteligenciaconhecimento',
            name='origem',
            field=models.CharField(choices=[('chat', 'Chat'), ('os_concluida', 'OS concluída'), ('catalogo', 'Catálogo'), ('manual', 'Manual')], default='chat', max_length=30),
        ),
        migrations.AddField(
            model_name='motorinteligenciaconhecimento',
            name='os_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conhecimentos_motor', to='ordens.ordemservico'),
        ),
        migrations.AddField(
            model_name='motorinteligenciaconhecimento',
            name='status_revisao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='aprovado', max_length=30),
        ),
        migrations.AddIndex(
            model_name='motorinteligenciaconhecimento',
            index=models.Index(fields=['origem', 'status_revisao'], name='estoque_mot_origem_1d03cc_idx'),
        ),
    ]
