# Generated by Django 5.1.4 on 2026-06-18 14:39

from django.db import migrations, models


LINKS_FONTES = {
    "planilha_custos": "https://www.gov.br/compras/pt-br/agente-publico/orientacoes-e-procedimentos/11-orientacoes-gerais-para-planilha-de-custos-e-formacao-de-precos",
    "compras_gov": "https://www.gov.br/compras/pt-br/sistemas/conheca-o-compras/pesquisa-de-precos",
    "catmat_catser": "https://catalogo.compras.gov.br/",
    "pncp": "https://pncp.gov.br/app/editais",
    "portal_transparencia": "https://www.portaltransparencia.gov.br/licitacoes/consulta",
    "sinapi": "https://www.caixa.gov.br/poder-publico/modernizacao-gestao/sinapi/Paginas/default.aspx",
    "historico_erp": "",
    "manual_tecnico": "",
}


def classificar_referencias_existentes(apps, schema_editor):
    ReferenciaPrecoPublico = apps.get_model("estoque", "ReferenciaPrecoPublico")
    base_legal_padrao = "Planilha de Custos e Formação de Preços; IN SEGES/ME 65/2021; Lei 14.133/2021 quando aplicável."
    for ref in ReferenciaPrecoPublico.objects.all():
        componente = "composicao"
        if ref.tipo_item == "produto":
            componente = "material"
        elif ref.tipo_item == "insumo":
            componente = "insumo"
        elif ref.tipo_item == "mao_obra":
            componente = "mao_obra"
        elif ref.codigo.startswith("REF-MOB"):
            componente = "deslocamento"
        elif ref.codigo.startswith("REF-CIVIL"):
            componente = "composicao"

        ref.componente_custo = componente
        ref.link_fonte = LINKS_FONTES.get(ref.fonte, "")
        ref.base_legal = base_legal_padrao
        ref.save(update_fields=["componente_custo", "link_fonte", "base_legal", "atualizado_em"])


def limpar_campos_classificacao(apps, schema_editor):
    ReferenciaPrecoPublico = apps.get_model("estoque", "ReferenciaPrecoPublico")
    ReferenciaPrecoPublico.objects.update(componente_custo="composicao", link_fonte="", base_legal="")


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_referenciaprecopublico'),
    ]

    operations = [
        migrations.AddField(
            model_name='referenciaprecopublico',
            name='base_legal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='referenciaprecopublico',
            name='componente_custo',
            field=models.CharField(choices=[('material', 'Material'), ('insumo', 'Insumo'), ('mao_obra', 'Mão de obra'), ('encargos', 'Encargos sociais/trabalhistas'), ('beneficios_despesas', 'Benefícios e despesas indiretas'), ('tributos', 'Tributos'), ('equipamento', 'Equipamento/ferramenta'), ('deslocamento', 'Deslocamento/logística'), ('composicao', 'Composição técnica')], default='composicao', max_length=30),
        ),
        migrations.AddField(
            model_name='referenciaprecopublico',
            name='link_fonte',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='referenciaprecopublico',
            name='fonte',
            field=models.CharField(choices=[('planilha_custos', 'Planilha de Custos e Formação de Preços'), ('compras_gov', 'Compras.gov / Pesquisa de Preços'), ('catmat_catser', 'CATMAT/CATSER'), ('pncp', 'Portal Nacional de Contratações Públicas'), ('portal_transparencia', 'Portal da Transparência'), ('sinapi', 'SINAPI'), ('historico_erp', 'Histórico ERP'), ('manual_tecnico', 'Base técnica manual')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='referenciaprecopublico',
            index=models.Index(fields=['componente_custo', 'ativo'], name='estoque_ref_compone_8f8fdd_idx'),
        ),
        migrations.RunPython(classificar_referencias_existentes, limpar_campos_classificacao),
    ]
