# Generated by Django 5.1.4 on 2026-05-07 19:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_cliente_principal_and_more'),
        ('ordens', '0014_chatos_origem_ordemservico_origem_referencia_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscopoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('icone', models.CharField(blank=True, max_length=80)),
                ('cor', models.CharField(default='#3B82F6', max_length=7)),
                ('descricao', models.TextField(blank=True)),
                ('norma_tecnica', models.CharField(blank=True, max_length=160)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Escopo técnico',
                'verbose_name_plural': 'Escopos técnicos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ContratoPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('objeto_contrato', models.TextField()),
                ('vigencia_meses', models.PositiveIntegerField(default=12)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('tipo_faturamento', models.CharField(choices=[('mensal_fixo', 'Mensal fixo'), ('por_os_executada', 'Por OS executada'), ('misto', 'Misto')], default='mensal_fixo', max_length=30)),
                ('dia_vencimento_fatura', models.PositiveIntegerField(default=10)),
                ('forma_pagamento', models.CharField(choices=[('boleto', 'Boleto'), ('pix', 'Pix'), ('transferencia', 'Transferência'), ('debito_aut', 'Débito automático')], default='boleto', max_length=30)),
                ('multa_atraso_percentual', models.DecimalField(decimal_places=3, default=Decimal('2.000'), max_digits=6)),
                ('juros_dia_percentual', models.DecimalField(decimal_places=3, default=Decimal('0.033'), max_digits=6)),
                ('multa_rescisao_antecipada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prazo_aviso_rescisao_dias', models.PositiveIntegerField(default=30)),
                ('reajuste_anual', models.BooleanField(default=True)),
                ('indice_reajuste', models.CharField(choices=[('IPCA', 'IPCA'), ('IGPM', 'IGP-M'), ('INPC', 'INPC'), ('fixo_percentual', 'Fixo percentual')], default='IPCA', max_length=30)),
                ('valor_reajuste_fixo', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('renovacao_automatica', models.BooleanField(default=False)),
                ('requer_art', models.BooleanField(default=False)),
                ('numero_art', models.CharField(blank=True, max_length=80)),
                ('pdf_art', models.FileField(blank=True, null=True, upload_to='contratos/art/')),
                ('responsavel_tecnico_crea', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativo', 'Ativo'), ('suspenso', 'Suspenso'), ('encerrado', 'Encerrado'), ('rescindido', 'Rescindido')], default='rascunho', max_length=20)),
                ('valor_total_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_total_contrato', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacoes', models.TextField(blank=True)),
                ('pdf_contrato', models.FileField(blank=True, null=True, upload_to='contratos/pdfs/')),
                ('pdf_proposta', models.FileField(blank=True, null=True, upload_to='contratos/propostas/')),
                ('pdf_cronograma', models.FileField(blank=True, null=True, upload_to='contratos/cronogramas/')),
                ('assinado_em', models.DateTimeField(blank=True, null=True)),
                ('assinado_por_cliente', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_preventiva', to='clientes.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_preventiva_criados', to=settings.AUTH_USER_MODEL)),
                ('responsavel_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_preventiva_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrato de preventiva',
                'verbose_name_plural': 'Contratos de preventiva',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EscopoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidade', models.CharField(choices=[('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('quadrimestral', 'Quadrimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=20)),
                ('equipamentos_quantidade', models.PositiveIntegerField(default=1)),
                ('equipamentos_descricao', models.TextField(blank=True)),
                ('valor_alocado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('escopo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escopos_unidade', to='contratos.escopotecnico')),
            ],
            options={
                'ordering': ['unidade_contrato__nome_unidade', 'escopo__ordem'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklistPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300)),
                ('categoria', models.CharField(choices=[('limpeza', 'Limpeza'), ('verificacao', 'Verificação'), ('medicao', 'Medição'), ('lubrificacao', 'Lubrificação'), ('troca', 'Troca'), ('ajuste', 'Ajuste'), ('teste', 'Teste'), ('inspecao', 'Inspeção')], max_length=30)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('requer_foto', models.BooleanField(default=False)),
                ('requer_medicao', models.BooleanField(default=False)),
                ('unidade_medicao', models.CharField(blank=True, max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('referencia_norma', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('escopo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_padrao', to='contratos.escopotecnico')),
            ],
            options={
                'verbose_name': 'Item de checklist padrão',
                'verbose_name_plural': 'Itens de checklist padrão',
                'ordering': ['escopo__ordem', 'ordem', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklistContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_customizada', models.TextField(blank=True)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('requer_foto', models.BooleanField(default=False)),
                ('requer_medicao', models.BooleanField(default=False)),
                ('unidade_medicao', models.CharField(blank=True, max_length=20)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('escopo_unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='contratos.escopounidade')),
                ('item_padrao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_contrato', to='contratos.itemchecklistpadrao')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_unidade', models.CharField(max_length=180)),
                ('codigo_interno', models.CharField(blank=True, max_length=60)),
                ('endereco_completo', models.TextField()),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('responsavel_local', models.CharField(blank=True, max_length=150)),
                ('telefone_local', models.CharField(blank=True, max_length=30)),
                ('email_local', models.EmailField(blank=True, max_length=254)),
                ('area_atendimento_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='contratos.contratopreventiva')),
            ],
            options={
                'ordering': ['nome_unidade'],
            },
        ),
        migrations.CreateModel(
            name='OSContratoPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_visita', models.PositiveIntegerField(default=1)),
                ('data_prevista', models.DateField()),
                ('data_executada', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('programada', 'Programada'), ('em_execucao', 'Em execução'), ('concluida', 'Concluída'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('checklist_completo', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_contrato', to='contratos.contratopreventiva')),
                ('escopo_unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_contrato', to='contratos.escopounidade')),
                ('ordem_servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_preventiva', to='ordens.ordemservico')),
                ('tecnico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_preventivas', to=settings.AUTH_USER_MODEL)),
                ('unidade_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='os_contrato', to='contratos.unidadecontrato')),
            ],
            options={
                'ordering': ['data_prevista', 'unidade_contrato__nome_unidade'],
                'unique_together': {('contrato', 'escopo_unidade', 'numero_visita', 'data_prevista')},
            },
        ),
        migrations.AddField(
            model_name='escopounidade',
            name='unidade_contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escopos', to='contratos.unidadecontrato'),
        ),
        migrations.CreateModel(
            name='EscopoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escopos_contrato', to='contratos.contratopreventiva')),
                ('escopo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contratos.escopotecnico')),
            ],
            options={
                'ordering': ['escopo__ordem'],
                'unique_together': {('contrato', 'escopo')},
            },
        ),
        migrations.CreateModel(
            name='FaturaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.PositiveIntegerField()),
                ('ano_referencia', models.PositiveIntegerField()),
                ('competencia', models.DateField()),
                ('vencimento', models.DateField()),
                ('valor_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_extras', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_glosa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('a_emitir', 'A emitir'), ('emitida', 'Emitida'), ('paga', 'Paga'), ('vencida', 'Vencida'), ('contestada', 'Contestada')], default='a_emitir', max_length=20)),
                ('numero_nf', models.CharField(blank=True, max_length=80)),
                ('pdf_nf', models.FileField(blank=True, null=True, upload_to='contratos/notas_fiscais/')),
                ('pdf_boletim_medicao', models.FileField(blank=True, null=True, upload_to='contratos/boletins/')),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='contratos.contratopreventiva')),
            ],
            options={
                'ordering': ['-ano_referencia', '-mes_referencia'],
                'unique_together': {('contrato', 'mes_referencia', 'ano_referencia')},
            },
        ),
        migrations.CreateModel(
            name='ExecucaoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('alerta', 'Alerta'), ('critico', 'Crítico'), ('nao_aplicavel', 'Não aplicável')], default='ok', max_length=20)),
                ('valor_medicao', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='contratos/checklist/')),
                ('executado_em', models.DateTimeField(blank=True, null=True)),
                ('executado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_preventiva_executados', to=settings.AUTH_USER_MODEL)),
                ('item_checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='contratos.itemchecklistcontrato')),
                ('os_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes_checklist', to='contratos.oscontratopreventiva')),
            ],
            options={
                'unique_together': {('os_contrato', 'item_checklist')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='escopounidade',
            unique_together={('unidade_contrato', 'escopo')},
        ),
    ]
