# Generated by Django 5.1.4 on 2026-05-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucaochecklist',
            name='status',
            field=models.CharField(choices=[('conforme', 'Conforme'), ('nao_conforme', 'Não conforme'), ('nao_aplicavel', 'Não aplicável'), ('corrigido_durante_visita', 'Corrigido durante a visita'), ('requer_orcamento', 'Requer orçamento'), ('requer_retorno_tecnico', 'Requer retorno técnico'), ('equipamento_parado', 'Equipamento parado'), ('operando_com_restricao', 'Equipamento operando com restrição')], default='conforme', max_length=32),
        ),
    ]
