# Generated by Django 5.1.4 on 2026-04-30 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_options_remove_cliente_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_portal', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Usuario do portal',
                'verbose_name_plural': 'Usuarios do portal',
                'ordering': ['email'],
            },
        ),
    ]
