# Generated by Django 5.1.4 on 2026-05-04 17:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_cliente_principal_and_more'),
        ('estoque', '0006_categorias_produto_padrao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('tipo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao_credito', 'Cartao credito'), ('cartao_debito', 'Cartao debito'), ('boleto', 'Boleto'), ('crediario', 'Crediario'), ('cheque', 'Cheque')], max_length=30)),
                ('aceita_troco', models.BooleanField(default=False)),
                ('taxa_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('prazo_recebimento_dias', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('razao_social', models.CharField(blank=True, max_length=180)),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('logradouro', models.CharField(blank=True, max_length=180)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=120)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('prazo_pagamento_padrao', models.PositiveIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('aberto', models.BooleanField(db_index=True, default=False)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('abertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechamento', models.DateTimeField(blank=True, null=True)),
                ('valor_abertura', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_fechamento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diferenca', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_loja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-abertura'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('previsao_entrega', models.DateField(blank=True, null=True)),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('numero_nf_fornecedor', models.CharField(blank=True, max_length=80)),
                ('pdf_nf', models.FileField(blank=True, null=True, upload_to='loja/pedidos/notas/')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_loja', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='loja.fornecedor')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendido_loja', models.BooleanField(default=True)),
                ('destaque', models.BooleanField(default=False)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='loja/produtos/')),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('promocao_ativa', models.BooleanField(default=False)),
                ('promocao_inicio', models.DateTimeField(blank=True, null=True)),
                ('promocao_fim', models.DateTimeField(blank=True, null=True)),
                ('ncm', models.CharField(blank=True, max_length=8)),
                ('cest', models.CharField(blank=True, max_length=20)),
                ('origem_produto', models.CharField(choices=[('nacional', 'Nacional'), ('importado', 'Importado'), ('estrangeira_direta', 'Estrangeira - importacao direta'), ('estrangeira_interna', 'Estrangeira - mercado interno')], default='nacional', max_length=40)),
                ('cfop_padrao', models.CharField(default='5102', max_length=4)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loja', to='estoque.produto')),
            ],
            options={
                'verbose_name': 'Produto da loja',
                'verbose_name_plural': 'Produtos da loja',
                'ordering': ['produto__nome'],
            },
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='loja/produtos/galeria/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('principal', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='loja.produtoloja')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_variacao', models.CharField(max_length=80)),
                ('valor_variacao', models.CharField(max_length=120)),
                ('codigo_barras', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('estoque_proprio', models.BooleanField(default=False)),
                ('preco_diferente', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='loja.produtoloja')),
            ],
            options={
                'verbose_name': 'Variacao do produto',
                'verbose_name_plural': 'Variacoes dos produtos',
                'ordering': ['produto', 'nome_variacao', 'valor_variacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='loja.pedidocompra')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_pedido_compra', to='loja.produtoloja')),
                ('variacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido_compra', to='loja.variacaoproduto')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True)),
                ('canal', models.CharField(choices=[('balcao', 'Balcao'), ('online', 'Online'), ('telefone', 'Telefone'), ('whatsapp', 'WhatsApp')], default='balcao', max_length=20)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('devolvida', 'Devolvida')], db_index=True, default='rascunho', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('desconto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacoes', models.TextField(blank=True)),
                ('nfc_e_emitida', models.BooleanField(default=False)),
                ('nfe_emitida', models.BooleanField(default=False)),
                ('numero_nf', models.CharField(blank=True, max_length=80)),
                ('chave_acesso_nf', models.CharField(blank=True, max_length=44)),
                ('pdf_nf', models.FileField(blank=True, null=True, upload_to='loja/notas/pdf/')),
                ('xml_nf', models.FileField(blank=True, null=True, upload_to='loja/notas/xml/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='loja.caixa')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_loja', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parcelas', models.PositiveIntegerField(default=1)),
                ('bandeira_cartao', models.CharField(blank=True, max_length=40)),
                ('numero_autorizacao', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('aprovado', 'Aprovado'), ('pendente', 'Pendente'), ('recusado', 'Recusado')], default='aprovado', max_length=20)),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='loja.formapagamento')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='loja.venda')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saida'), ('sangria', 'Sangria'), ('suprimento', 'Suprimento')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='loja.caixa')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to='loja.formapagamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_caixa', to='loja.venda')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('desconto_item', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comissao_vendedor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='loja.produtoloja')),
                ('variacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_venda', to='loja.variacaoproduto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='loja.venda')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EntregaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('retirada', 'Retirada'), ('entrega_propria', 'Entrega propria'), ('transportadora', 'Transportadora'), ('correios', 'Correios')], default='retirada', max_length=30)),
                ('endereco_entrega', models.TextField(blank=True)),
                ('transportadora', models.CharField(blank=True, max_length=120)),
                ('codigo_rastreio', models.CharField(blank=True, max_length=120)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('previsao_entrega', models.DateField(blank=True, null=True)),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('preparando', 'Preparando'), ('enviado', 'Enviado'), ('em_transito', 'Em transito'), ('entregue', 'Entregue'), ('devolvido', 'Devolvido')], default='preparando', max_length=30)),
                ('entregador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_loja', to=settings.AUTH_USER_MODEL)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='loja.venda')),
            ],
            options={
                'ordering': ['previsao_entrega', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_vendedor', models.CharField(max_length=30, unique=True)),
                ('comissao_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ativo', models.BooleanField(default=True)),
                ('meta_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_loja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['codigo_vendedor'],
            },
        ),
        migrations.AddField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='loja.vendedor'),
        ),
    ]
