# Generated by Django 5.1.4 on 2026-05-05 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('hvac', 'HVAC'), ('eletrica', 'Elétrica'), ('hidraulica', 'Hidráulica'), ('civil', 'Civil'), ('ti', 'TI'), ('seguranca', 'Segurança'), ('outro', 'Outro')], max_length=20)),
                ('localizacao_predio', models.CharField(blank=True, max_length=100)),
                ('localizacao_andar', models.CharField(blank=True, max_length=50)),
                ('localizacao_sala', models.CharField(blank=True, max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='facilities/ativos/')),
                ('manual_url', models.URLField(blank=True)),
                ('data_instalacao', models.DateField(blank=True, null=True)),
                ('vida_util_anos', models.PositiveIntegerField(blank=True, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('operacional', 'Operacional'), ('em_manutencao', 'Em Manutenção'), ('inativo', 'Inativo'), ('sucateado', 'Sucateado')], default='operacional', max_length=20)),
                ('custo_aquisicao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ativo',
                'verbose_name_plural': 'Ativos',
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='ContratoTerceirizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor_nome', models.CharField(max_length=200)),
                ('fornecedor_cnpj', models.CharField(blank=True, max_length=18)),
                ('tipo_servico', models.CharField(max_length=100)),
                ('valor_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('periodicidade_servico', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral')], max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('vencendo', 'Vencendo'), ('vencido', 'Vencido'), ('rescindido', 'Rescindido')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('avaliacao_fornecedor', models.PositiveIntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contrato Terceirizado',
                'verbose_name_plural': 'Contratos Terceirizados',
                'ordering': ['data_fim'],
            },
        ),
        migrations.CreateModel(
            name='ChamadoFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em Atendimento'), ('aguardando', 'Aguardando'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=20)),
                ('solicitante_nome', models.CharField(max_length=100)),
                ('solicitante_email', models.CharField(blank=True, max_length=100)),
                ('solicitante_ramal', models.CharField(blank=True, max_length=20)),
                ('local', models.CharField(blank=True, max_length=200)),
                ('sla_horas', models.PositiveIntegerField(default=8)),
                ('aberto_em', models.DateTimeField(auto_now_add=True)),
                ('resolvido_em', models.DateTimeField(blank=True, null=True)),
                ('avaliacao', models.PositiveIntegerField(blank=True, null=True)),
                ('comentario_avaliacao', models.TextField(blank=True)),
                ('foto_antes', models.ImageField(blank=True, null=True, upload_to='facilities/chamados/')),
                ('foto_depois', models.ImageField(blank=True, null=True, upload_to='facilities/chamados/')),
                ('ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados', to='facilities.ativo')),
                ('tecnico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_facilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chamado Facilities',
                'verbose_name_plural': 'Chamados Facilities',
                'ordering': ['-aberto_em'],
            },
        ),
        migrations.CreateModel(
            name='PlanoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('preventiva', 'Preventiva'), ('preditiva', 'Preditiva'), ('corretiva', 'Corretiva'), ('emergencia', 'Emergência')], max_length=20)),
                ('periodicidade', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('proxima_execucao', models.DateField(blank=True, null=True)),
                ('ultima_execucao', models.DateField(blank=True, null=True)),
                ('ativo_plano', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='facilities.ativo')),
            ],
            options={
                'verbose_name': 'Plano de Manutenção',
                'verbose_name_plural': 'Planos de Manutenção',
                'ordering': ['proxima_execucao'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('descricao', models.CharField(max_length=300)),
                ('obrigatorio', models.BooleanField(default=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='facilities.planomanutencao')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ProjetoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('construcao', 'Construção'), ('reforma', 'Reforma'), ('instalacao', 'Instalação'), ('ampliacao', 'Ampliação'), ('outro', 'Outro')], max_length=20)),
                ('status', models.CharField(choices=[('planejamento', 'Planejamento'), ('em_andamento', 'Em Andamento'), ('pausado', 'Pausado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='planejamento', max_length=20)),
                ('orcamento_previsto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('orcamento_realizado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('data_inicio_prevista', models.DateField(blank=True, null=True)),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('data_inicio_real', models.DateField(blank=True, null=True)),
                ('data_fim_real', models.DateField(blank=True, null=True)),
                ('percentual_concluido', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_obra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto/Obra',
                'verbose_name_plural': 'Projetos/Obras',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='FaseObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('percentual_concluido', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='pendente', max_length=20)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='facilities.projetoobra')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='DiarioObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('clima', models.CharField(blank=True, choices=[('sol', 'Sol'), ('nublado', 'Nublado'), ('chuva', 'Chuva'), ('vento', 'Vento')], max_length=10)),
                ('equipe_presente', models.PositiveIntegerField(default=0)),
                ('atividades_realizadas', models.TextField()),
                ('ocorrencias', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='facilities/diario/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diarios_obra', to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diarios', to='facilities.projetoobra')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='BoletimMedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('mes_referencia', models.DateField()),
                ('percentual_executado', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_medido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='rascunho', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletins', to='facilities.projetoobra')),
            ],
            options={
                'ordering': ['-mes_referencia'],
            },
        ),
    ]
