# Generated by Django 5.1.4 on 2026-05-05 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_servico', models.CharField(max_length=100)),
                ('modo', models.CharField(choices=[('aberta', 'Aberta (qualquer prestador)'), ('convidada', 'Convidada')], default='aberta', max_length=20)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('publicada', 'Publicada'), ('em_analise', 'Em Análise'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='rascunho', max_length=20)),
                ('prazo_propostas', models.DateTimeField(blank=True, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licitacoes', to='facilities.ativo')),
            ],
            options={
                'verbose_name': 'Licitação',
                'verbose_name_plural': 'Licitações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PropostaLicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestador_nome', models.CharField(max_length=200)),
                ('prestador_email', models.EmailField(max_length=254)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14)),
                ('prazo_execucao_dias', models.PositiveIntegerField()),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='enviada', max_length=20)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('licitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='facilities.licitacao')),
            ],
            options={
                'verbose_name': 'Proposta de Licitação',
                'verbose_name_plural': 'Propostas de Licitação',
                'ordering': ['enviado_em'],
            },
        ),
    ]
