# Generated by Django 5.1.4 on 2026-05-06 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_licitacao_propostalicitacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_type', models.CharField(max_length=50)),
                ('aggregate_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('processado', 'Processado'), ('falhou', 'Falhou')], default='pendente', max_length=20)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('proxima_tentativa', models.DateTimeField(auto_now_add=True)),
                ('erro_ultimo', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Outbox Message',
                'verbose_name_plural': 'Outbox Messages',
                'ordering': ['criado_em'],
            },
        ),
        migrations.AddField(
            model_name='propostalicitacao',
            name='condicao_pagamento',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='propostalicitacao',
            name='itens_orcamento',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='propostalicitacao',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='propostalicitacao',
            name='validade_proposta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propostalicitacao',
            name='prestador_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='propostalicitacao',
            name='prestador_nome',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
