# Generated by Django 5.1.4 on 2026-05-06 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_outboxmessage_propostalicitacao_condicao_pagamento_and_more'),
        ('saas', '0002_outboxmessage_licitacao_propostalicitacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacao',
            name='prestadores_convidados',
            field=models.ManyToManyField(blank=True, related_name='convites_licitacao_facilities', to='saas.tenant'),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='tenant_contratante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licitacoes_facilities', to='saas.tenant'),
        ),
    ]
