# Generated by Django 5.1.4 on 2026-05-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_licitacao_prestadores_convidados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacao',
            name='aprovada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='budget_mensal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='ordem_servico_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacao',
            name='valor_budget_reservado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
