# Generated by Django 5.1.4 on 2026-05-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_licitacao_aprovada_em_licitacao_budget_mensal_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostalicitacao',
            name='tenant_prestador_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
