# Generated by Django 5.1.4 on 2026-05-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0006_propostalicitacao_tenant_prestador_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='propostalicitacao',
            name='arquivo_proposta',
            field=models.FileField(blank=True, null=True, upload_to='facilities/propostas/'),
        ),
    ]
