# Generated by Django 5.1.4 on 2026-05-28 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_propostalicitacao_arquivo_proposta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadofacilities',
            name='chamado_plataforma_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='chamadofacilities',
            name='ordem_servico_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='chamadofacilities',
            name='origem_sistema',
            field=models.CharField(db_index=True, default='facilities', max_length=30),
        ),
        migrations.AddField(
            model_name='chamadofacilities',
            name='tenant_contratante_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='chamadofacilities',
            name='tenant_prestador_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ComunicacaoPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(choices=[('chamado', 'Chamado'), ('licitacao', 'Licitação'), ('ordem', 'Ordem de Serviço')], max_length=30)),
                ('ordem_servico_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('tenant_contratante_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('tenant_prestador_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('origem_sistema', models.CharField(choices=[('contratante', 'Contratante'), ('prestador', 'Prestador'), ('sistema', 'Sistema')], default='prestador', max_length=30)),
                ('usuario_nome', models.CharField(blank=True, max_length=150)),
                ('mensagem', models.TextField()),
                ('anexos', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('lido_contratante', models.BooleanField(default=False)),
                ('lido_prestador', models.BooleanField(default=False)),
                ('chamado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_plataforma', to='facilities.chamadofacilities')),
                ('licitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_plataforma', to='facilities.licitacao')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem de plataforma',
                'verbose_name_plural': 'Mensagens de plataforma',
                'ordering': ['criado_em', 'id'],
                'indexes': [models.Index(fields=['escopo', 'criado_em'], name='facilities__escopo_0305a9_idx'), models.Index(fields=['tenant_contratante_id', 'tenant_prestador_id'], name='facilities__tenant__1d0674_idx')],
            },
        ),
    ]
