# Generated by Django 5.1.4 on 2026-05-28 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_chamadofacilities_chamado_plataforma_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ativo',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='garantia_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ativo',
            name='unidade_nome',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='chamadofacilities',
            name='centro_custo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='chamadofacilities',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamadofacilities',
            name='custo_extra_descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chamadofacilities',
            name='custo_extra_status',
            field=models.CharField(choices=[('sem_custo', 'Sem custo extra'), ('pendente', 'Pendente de aprovação'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], default='sem_custo', max_length=30),
        ),
        migrations.AddField(
            model_name='chamadofacilities',
            name='custo_extra_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='chamadofacilities',
            name='em_rota_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamadofacilities',
            name='inicio_execucao_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chamadofacilities',
            name='nps',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planomanutencao',
            name='gerar_relatorio_pmoc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='planomanutencao',
            name='norma_referencia',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='planomanutencao',
            name='notificar_dias_antes',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='chamadofacilities',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_rota', 'Em Rota'), ('em_atendimento', 'Em Atendimento'), ('em_execucao', 'Em Execução'), ('aguardando', 'Aguardando'), ('aguardando_aprovacao', 'Aguardando Aprovação'), ('resolvido', 'Resolvido'), ('concluido', 'Concluído'), ('fechado', 'Fechado')], default='aberto', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentoFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('art', 'ART'), ('laudo', 'Laudo'), ('garantia', 'Garantia'), ('pmoc', 'PMOC'), ('nr', 'NR / Certificado'), ('outro', 'Outro')], default='outro', max_length=30)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='facilities/documentos/')),
                ('url', models.URLField(blank=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, db_index=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='facilities.ativo')),
                ('chamado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='facilities.chamadofacilities')),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='facilities.planomanutencao')),
            ],
            options={
                'verbose_name': 'Documento Facilities',
                'verbose_name_plural': 'Documentos Facilities',
                'ordering': ['data_validade', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executado_em', models.DateTimeField(auto_now_add=True)),
                ('checklist_respostas', models.JSONField(blank=True, default=list)),
                ('observacoes', models.TextField(blank=True)),
                ('foto_antes', models.ImageField(blank=True, null=True, upload_to='facilities/preventiva/')),
                ('foto_depois', models.ImageField(blank=True, null=True, upload_to='facilities/preventiva/')),
                ('assinatura_digital', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('relatorio_pmoc', models.FileField(blank=True, null=True, upload_to='facilities/pmoc/')),
                ('chamado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execucoes_preventiva', to='facilities.chamadofacilities')),
                ('executado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='facilities.planomanutencao')),
            ],
            options={
                'verbose_name': 'Execução de Manutenção',
                'verbose_name_plural': 'Execuções de Manutenção',
                'ordering': ['-executado_em'],
            },
        ),
    ]
