# Generated by Django 5.1.4 on 2026-05-04 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Terceirizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('nome_fantasia', models.CharField(blank=True, max_length=180)),
                ('razao_social', models.CharField(blank=True, max_length=180)),
                ('tipo_pessoa', models.CharField(choices=[('fisica', 'Pessoa fisica'), ('juridica', 'Pessoa juridica')], default='juridica', max_length=20)),
                ('documento', models.CharField(blank=True, db_index=True, max_length=20)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('especialidades', models.CharField(blank=True, max_length=255)),
                ('estado_base', models.CharField(blank=True, db_index=True, max_length=2)),
                ('cidade_base', models.CharField(blank=True, max_length=120)),
                ('atende_estados', models.CharField(blank=True, max_length=255)),
                ('chave_pix', models.CharField(blank=True, max_length=180)),
                ('tipo_chave_pix', models.CharField(blank=True, max_length=40)),
                ('banco', models.CharField(blank=True, max_length=120)),
                ('agencia', models.CharField(blank=True, max_length=30)),
                ('conta', models.CharField(blank=True, max_length=40)),
                ('tipo_conta', models.CharField(blank=True, max_length=40)),
                ('markup_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('bloqueado', 'Bloqueado')], db_index=True, default='ativo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_terceirizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Terceirizado',
                'verbose_name_plural': 'Terceirizados',
                'ordering': ['nome'],
            },
        ),
    ]
