# Generated by Django 5.1.4 on 2026-04-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('os_atribuida', 'OS atribuida'), ('os_agendada_amanha', 'OS agendada amanha'), ('os_finalizada', 'OS finalizada'), ('pagamento_atrasado', 'Pagamento atrasado'), ('estoque_baixo', 'Estoque baixo'), ('relatorio_finalizado', 'Relatorio finalizado')], max_length=40)),
                ('destinatario', models.EmailField(max_length=254)),
                ('conteudo', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de notificacao',
                'verbose_name_plural': 'Logs de notificacao',
                'ordering': ['-criado_em'],
            },
        ),
    ]
