# Generated by Django 5.1.4 on 2026-05-05 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_atribuida', models.CharField(choices=[('instantanea', 'Instantânea'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('desativada', 'Desativada')], default='instantanea', max_length=20)),
                ('os_aprovada', models.CharField(choices=[('instantanea', 'Instantânea'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('desativada', 'Desativada')], default='instantanea', max_length=20)),
                ('lembranca_agendamento', models.CharField(choices=[('instantanea', 'Instantânea'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('desativada', 'Desativada')], default='instantanea', max_length=20)),
                ('os_finalizada', models.CharField(choices=[('instantanea', 'Instantânea'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('desativada', 'Desativada')], default='instantanea', max_length=20)),
                ('pagamento_atrasado', models.CharField(choices=[('instantanea', 'Instantânea'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('desativada', 'Desativada')], default='diaria', max_length=20)),
                ('estoque_baixo', models.CharField(choices=[('instantanea', 'Instantânea'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('desativada', 'Desativada')], default='semanal', max_length=20)),
                ('relatorio_pronto', models.CharField(choices=[('instantanea', 'Instantânea'), ('diaria', 'Diária'), ('semanal', 'Semanal'), ('desativada', 'Desativada')], default='instantanea', max_length=20)),
                ('enviar_email', models.BooleanField(default=True)),
                ('enviar_whatsapp', models.BooleanField(default=False)),
                ('numero_whatsapp', models.CharField(blank=True, max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de notificação',
                'verbose_name_plural': 'Configurações de notificação',
            },
        ),
        migrations.AddField(
            model_name='lognotificacao',
            name='canal',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('interno', 'Notificação Interna')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='lognotificacao',
            name='dados_adicionais',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lognotificacao',
            name='erro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lognotificacao',
            name='ordem_servico_id',
            field=models.IntegerField(blank=True, help_text='ID da OS relacionada', null=True),
        ),
        migrations.AddField(
            model_name='lognotificacao',
            name='proxima_tentativa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lognotificacao',
            name='tentativas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lognotificacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lognotificacao',
            name='tipo',
            field=models.CharField(choices=[('os_atribuida', 'OS atribuida'), ('os_aprovada', 'OS aprovada'), ('os_agendada_amanha', 'OS agendada amanha'), ('os_finalizada', 'OS finalizada'), ('pagamento_atrasado', 'Pagamento atrasado'), ('estoque_baixo', 'Estoque baixo'), ('relatorio_finalizado', 'Relatorio finalizado')], max_length=40),
        ),
        migrations.AddIndex(
            model_name='lognotificacao',
            index=models.Index(fields=['-criado_em'], name='notificacoe_criado__32a968_idx'),
        ),
        migrations.AddIndex(
            model_name='lognotificacao',
            index=models.Index(fields=['status'], name='notificacoe_status_973b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='lognotificacao',
            index=models.Index(fields=['tipo'], name='notificacoe_tipo_bd01f4_idx'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config_notificacoes', to=settings.AUTH_USER_MODEL),
        ),
    ]
