# Generated by Django 5.1.4 on 2026-04-30 17:43

import apps.usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('cpf', models.CharField(blank=True, max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='usuarios/avatar/')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('financeiro', 'Financeiro'), ('comercial', 'Comercial'), ('tecnico', 'Tecnico'), ('estoquista', 'Estoquista'), ('suporte', 'Suporte')], default='tecnico', max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('departamento', models.CharField(blank=True, max_length=120)),
                ('tipo_contratacao', models.CharField(choices=[('clt', 'CLT'), ('pj', 'PJ'), ('estagiario', 'Estagiario'), ('terceirizado', 'Terceirizado'), ('freelancer', 'Freelancer')], default='clt', max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('bloqueado', 'Bloqueado'), ('ferias', 'Ferias'), ('afastado', 'Afastado')], default='ativo', max_length=20)),
                ('matricula', models.CharField(blank=True, max_length=30, unique=True)),
                ('data_admissao', models.DateField(blank=True, null=True)),
                ('data_desligamento', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=120)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('contato_emergencia_nome', models.CharField(blank=True, max_length=150)),
                ('contato_emergencia_telefone', models.CharField(blank=True, max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('ultimo_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ultimo_login_em', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['first_name', 'last_name', 'email'],
            },
            managers=[
                ('objects', apps.usuarios.models.UsuarioManager()),
            ],
        ),
    ]
