# Generated by Django 5.1.4 on 2026-05-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('financeiro', 'Financeiro'), ('comercial', 'Comercial'), ('tecnico', 'Tecnico'), ('estoquista', 'Estoquista'), ('suporte', 'Suporte'), ('vendedor_loja', 'Vendedor loja'), ('gerente_loja', 'Gerente loja')], default='tecnico', max_length=20),
        ),
    ]
