# Generated by Django 5.1.4 on 2026-05-05 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modulo',
            field=models.CharField(choices=[('erp', 'ERP Nexus (Prestador)'), ('facilities', 'Facilities Platform (Contratante)'), ('ambos', 'Ambos os produtos')], default='erp', help_text='Define para qual produto este usuário tem acesso', max_length=20),
        ),
    ]
