# Generated by Django 5.1.4 on 2026-06-22 14:17

from django.db import migrations, models


def normalizar_campos_unicos_opcionais(apps, schema_editor):
    Usuario = apps.get_model("usuarios", "Usuario")
    Usuario.objects.filter(cpf="").update(cpf=None)
    Usuario.objects.filter(matricula="").update(matricula=None)


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_add_modulo_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.RunPython(
            normalizar_campos_unicos_opcionais,
            migrations.RunPython.noop,
        ),
    ]
