# Generated by Django 5.1.4 on 2026-07-02 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEmissorFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Emissor padrão', max_length=120)),
                ('provedor', models.CharField(choices=[('mock', 'Simulador interno'), ('focus_nfe', 'Focus NFe'), ('enotas', 'eNotas'), ('tecnospeed', 'TecnoSpeed'), ('nfe_io', 'NFE.io'), ('biblioteca_python', 'Biblioteca Python')], default='mock', max_length=40)),
                ('ambiente', models.CharField(choices=[('homologacao', 'Homologação'), ('producao', 'Produção')], default='homologacao', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('credenciais', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de emissor fiscal',
                'verbose_name_plural': 'Configurações de emissores fiscais',
                'ordering': ['-ativo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoFiscalEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(default='NFS-e', max_length=12)),
                ('ambiente', models.CharField(choices=[('homologacao', 'Homologação'), ('producao', 'Produção')], max_length=20)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado'), ('autorizado', 'Autorizado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20)),
                ('chave_acesso', models.CharField(blank=True, max_length=80)),
                ('numero', models.CharField(blank=True, max_length=40)),
                ('serie', models.CharField(blank=True, max_length=20)),
                ('protocolo', models.CharField(blank=True, max_length=80)),
                ('payload_enviado', models.JSONField(blank=True, default=dict)),
                ('retorno_provedor', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('emissor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='fiscal_emission.configuracaoemissorfiscal')),
            ],
            options={
                'verbose_name': 'Documento fiscal emitido',
                'verbose_name_plural': 'Documentos fiscais emitidos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
