# Generated by Django 5.1.4 on 2026-07-02 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscal_emission', '0001_initial'),
        ('fiscal_rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscalemitido',
            name='operacao_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_emitidos', to='fiscal_rules.operacaofiscal'),
        ),
    ]
